# Generated by Django 4.2 on 2024-04-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_member_training_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
